# Open API_ Air Condition
### JSON 타입의 API 처리하기


In [5]:
import requests
from bs4 import BeautifulSoup

In [29]:
url='http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty'

param_data={'sidoName':'대구',
            'pageNo':'1',
            'numOfRows':'1000',
            'returnType':'json',
            'serviceKey':'hv2kRgNo//Csty9EFczwIBosa8NffACY+jyKfHWZ0po2erSkH+uGEBEsbbEFniTtEKR/9n4D2X3tY6Idc1XvQQ==',
            'ver':'1.0'
           }

#servicekey=decoding key를 넣어줘야함
#.py로 해야하는 이유 : window가 call할수 있기때문에 ->  주기적으로 업데이트 되는 api이기 때문에 schduling을 하여 주기적으로 데이터를 받아와서 
#DB에 넣어주는작업을 해야함 (리눅스 Schduler:Cron사용)
#때에 따라 발생하는 exception을 다 처리해야함
#exception이 발생하는지 확인해야함 
#ex) 관리자에게 알림, 

In [11]:
res=requests.get(url,params=param_data)

In [12]:
print(res.text)

{"response":{"body":{"totalCount":20,"items":[{"so2Grade":"1","coFlag":null,"khaiValue":"60","so2Value":"0.002","coValue":"0.2","pm25Flag":null,"pm10Flag":null,"o3Grade":"2","pm10Value":"37","khaiGrade":"2","pm25Value":"5","sidoName":"대구","no2Flag":null,"no2Grade":"1","o3Flag":null,"pm25Grade":"1","so2Flag":null,"dataTime":"2022-02-05 15:00","coGrade":"1","no2Value":"0.008","stationName":"수창동","pm10Grade":"1","o3Value":"0.042"},{"so2Grade":"1","coFlag":null,"khaiValue":"53","so2Value":"0.004","coValue":"0.3","pm25Flag":null,"pm10Flag":null,"o3Grade":"2","pm10Value":"33","khaiGrade":"2","pm25Value":"10","sidoName":"대구","no2Flag":null,"no2Grade":"1","o3Flag":null,"pm25Grade":"1","so2Flag":null,"dataTime":"2022-02-05 15:00","coGrade":"1","no2Value":"0.007","stationName":"지산동","pm10Grade":"2","o3Value":"0.033"},{"so2Grade":"1","coFlag":null,"khaiValue":"-","so2Value":"0.002","coValue":"0.3","pm25Flag":null,"pm10Flag":null,"o3Grade":"2","pm10Value":"37","khaiGrade":null,"pm25Value":"8","sid

In [13]:
data=res.json()
#json 형태를 dictonary형태로 가져옴
print(data)


{'response': {'body': {'totalCount': 20, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '5', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '수창동', 'pm10Grade': '1', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '53', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '지산동', 'pm10Grade': '2', 'o3Value': '0.033'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': 

In [18]:
Infos=data['response']['body']['items']

In [19]:
print(Infos)

[{'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '5', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '수창동', 'pm10Grade': '1', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '53', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '지산동', 'pm10Grade': '2', 'o3Value': '0.033'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grad

In [23]:
list_dic=[]
for Info in Infos:
    list_dic.append(Info)
print(list_dic)


[{'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '5', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '수창동', 'pm10Grade': '1', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '53', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '대구', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2022-02-05 15:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '지산동', 'pm10Grade': '2', 'o3Value': '0.033'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grad

In [28]:
for i in list_dic:
    key_arrays=i.keys()
    print('')
    for key_array in key_arrays:
        print(key_array,':',i[key_array])
    


so2Grade : 1
coFlag : None
khaiValue : 60
so2Value : 0.002
coValue : 0.2
pm25Flag : None
pm10Flag : None
o3Grade : 2
pm10Value : 37
khaiGrade : 2
pm25Value : 5
sidoName : 대구
no2Flag : None
no2Grade : 1
o3Flag : None
pm25Grade : 1
so2Flag : None
dataTime : 2022-02-05 15:00
coGrade : 1
no2Value : 0.008
stationName : 수창동
pm10Grade : 1
o3Value : 0.042

so2Grade : 1
coFlag : None
khaiValue : 53
so2Value : 0.004
coValue : 0.3
pm25Flag : None
pm10Flag : None
o3Grade : 2
pm10Value : 33
khaiGrade : 2
pm25Value : 10
sidoName : 대구
no2Flag : None
no2Grade : 1
o3Flag : None
pm25Grade : 1
so2Flag : None
dataTime : 2022-02-05 15:00
coGrade : 1
no2Value : 0.007
stationName : 지산동
pm10Grade : 2
o3Value : 0.033

so2Grade : 1
coFlag : None
khaiValue : -
so2Value : 0.002
coValue : 0.3
pm25Flag : None
pm10Flag : None
o3Grade : 2
pm10Value : 37
khaiGrade : None
pm25Value : 8
sidoName : 대구
no2Flag : None
no2Grade : 1
o3Flag : None
pm25Grade : None
so2Flag : None
dataTime : 2022-02-05 15:00
coGrade : 1
no2Val

### numpy 연습

In [30]:
import numpy as np

In [32]:
chart=np.zeros((3,4))
print(chart)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
chart1=np.zeros((2,3))
print(chart1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
chart2=np.zeros((2,3,2))
print(chart2)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [43]:
dd=np.ones((1,2),dtype=np.float64)

In [44]:
print(dd)

[[1. 1.]]


In [41]:
aa=[1,2,3.0]
print(type(aa))

<class 'list'>


In [45]:
string_dd=np.ones((1,2),dtype=np.string_)
print(string_dd)

[[b'1' b'1']]


In [48]:
arr=np.array([3,4,5])
arr=arr.astype(float)
print(arr)

[3. 4. 5.]


In [49]:
pp=np.ones((2,3,4),dtype=np.int64)
print(pp)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [50]:
ppp=np.zeros((2,3),dtype=np.int64)
print(ppp)

[[0 0 0]
 [0 0 0]]
